### ISSUE TITLE
Love the way of feedback.

### ISSUE THREAD

**Issue by worotyns** [zodvik/zodvik.com#1]
Smart use of github issues. :)
PS. Add `<a target="_blank">` to "Share feedback" it will help to write feedback and see article.

**Comment by zodvik** [comment]
Thanks!

> PS. Add to "Share feedback" it will help to write feedback and see article.

@worotyns Sorry, could you please elaborate on this?

**Comment by worotyns** [comment]
> Thanks!
> 
> > PS. Add to "Share feedback" it will help to write feedback and see article.
> 
> @worotyns Sorry, could you please elaborate on this?

I edited previous comment, github render `<a>` tag, and you don't see whole context.

**Comment by zodvik** [comment]
that makes complete sense. thanks for flagging this!

**Comment by zodvik** [comment]
fixed!
