### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by rahimnathwani** [zodvik/zodvik.com#2]
"that let’s anyone" should be "that lets anyone"

**Comment by zodvik** [comment]
Thanks.

Made a few fixes in https://github.com/zodvik/zodvik.com/commit/994072f1cb9f890beecdc64122f918874a0bea22 and https://github.com/zodvik/zodvik.com/commit/62e917ee96748e982b93b4bb9f780cb3184bfa9b.
